version: '3.8'

services:
  # 1. MESSAGE QUEUE
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sentinel_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Port App kết nối (AMQP)
      - "15672:15672" # Port Dashboard quản lý
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - sentinel_network

  # 2. CACHE & KEY-VALUE STORE (Redis)
  redis:
    image: redis:7-alpine
    container_name: sentinel_redis
    restart: always
    ports:
      - "6379:6379"
    # Lệnh này đặt mật khẩu cho Redis
    command: redis-server --requirepass sentinel_redis_pass
    volumes:
      - redis_data:/data
    networks:
      - sentinel_network

  # 3. OBJECT STORAGE (MinIO - Giả lập S3)
  minio:
    image: minio/minio
    container_name: sentinel_minio
    restart: always
    ports:
      - "9000:9000" # Port API
      - "9001:9001" # Port Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - sentinel_network

  # 4. DATABASE (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: sentinel_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 744879
      POSTGRES_DB: sentinel_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentinel_network

# Nơi lưu trữ dữ liệu bền vững
volumes:
  rabbitmq_data:
  redis_data:
  minio_data:
  postgres_data:

# Định nghĩa mạng chung cho hệ thống
networks:
  sentinel_network:
    driver: bridge