spring.application.name=sentinel-core
server.port=8080

# --- 1. C?U HÌNH DATABASE ---
spring.datasource.url=jdbc:postgresql://localhost:5433/sentinel_db 
spring.datasource.username=postgres
# M?t kh?u kh?p v?i docker-compose.yml
spring.datasource.password=744879

# --- 2. C?U HÌNH JPA/HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- 3. C?U HÌNH JWT (B?O M?T) ---
sentinel.app.jwtSecret=JpaU+uGN6c9h8nbJWO6SMB9M4CCb8bLu4SXNnXiJGsLax56uJH19NknPoJ90Qqbr
# Th?i gian h?t h?n (ms) - 24 gi?
sentinel.app.jwtExpirationMs=86400000

# --- 4. C?U HÌNH RABBITMQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123