spring.application.name=sentinel-core

server.port=8080

# 2. C?u hình k?t n?i Database (QUAN TR?NG: B?n hãy s?a 3 dòng d??i cho ?úng máy b?n)
# N?u b?n ch?y SQL vào database tên 'postgres' thì ?? là /postgres
# N?u b?n ?ã t?o DB riêng tên 'sentinel' thì ??i thành /sentinel
spring.datasource.url=jdbc:postgresql://localhost:5432/Distributed_AI_Surveillance_Storage
spring.datasource.username=postgres
spring.datasource.password=744879

# 3. C?u hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true